name = "nimbus-worker"
main = "src/index.ts"
compatibility_date = "2024-03-29"

[observability]
enabled = true

# STAGING ENVIRONMENT
[env.staging]
name = "nimbus-worker-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "nimbus-db-staging"
database_id = "707b6c9b-e90d-40ad-a954-1dc6910071ee"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "74cf280630f749e3aaee3c588c425509"

[env.staging.triggers]
crons = ["0 0 * * *"] 

[env.staging.observability]
enabled = true

# PRODUCTION ENVIRONMENT
[env.production]
name = "nimbus-worker-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "nimbus-db-prod"
database_id = "c52950d9-666a-4077-b3c3-0c5f326abeda"

[[env.production.kv_namespaces]]
binding = "KV"
id = "14cb432af330454bb33764e4e80a4b87"

[env.production.triggers]
crons = ["0 0 * * *"]

[env.production.observability]
enabled = true
